### ISSUE TITLE
Broken dependancies

### ISSUE THREAD

**Issue by freman** [sujit-baniya/phonenumbers#1]
go get: github.com/sujit-baniya/phonenumbers@none updating to
	github.com/sujit-baniya/phonenumbers@v1.0.71 requires
	github.com/sujit-baniya/utils@v0.0.2: reading github.com/sujit-baniya/utils/go.mod at revision v0.0.2: unknown revision v0.0.2

**Comment by sujit-baniya** [comment]
@freman Thanks for the report. I've fixed the issue.

The dependency is private. So I've removed the dependency for now.
